/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;
import java.util.ArrayList;
import java.util.HashMap;
import oru.inf.InfDB;
import oru.inf.InfException;






/**
 *
 * @author diyar
 */
public class MinaProjekt extends javax.swing.JFrame {
    private InfDB idb;
    private String inloggadAnvandare;
    

    /**
     * Creates new form MinaProjekt
     */
    public MinaProjekt(InfDB idb,String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        minaprojekt();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Txtprojekt1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Txtprojekt2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Txtprojekt3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Txtprojekt4 = new javax.swing.JTextArea();
        Txtbeskrivning = new javax.swing.JTextField();
        Txtbeskrivning1 = new javax.swing.JTextField();
        Txtprojektnamn = new javax.swing.JTextField();
        Txtprojektnamn1 = new javax.swing.JTextField();
        Txtbeskrivning2 = new javax.swing.JTextField();
        Txtprojektnamn2 = new javax.swing.JTextField();
        Txtstartdatum2 = new javax.swing.JTextField();
        Txtslutdatum2 = new javax.swing.JTextField();
        Txtkostnad2 = new javax.swing.JTextField();
        Txtprioritet2 = new javax.swing.JTextField();
        Txtprojektnamn3 = new javax.swing.JTextField();
        Txtstartdatum3 = new javax.swing.JTextField();
        Txtslutdatum3 = new javax.swing.JTextField();
        Txtkostnad3 = new javax.swing.JTextField();
        Txtstatus3 = new javax.swing.JTextField();
        Txtprioritet3 = new javax.swing.JTextField();
        Txtprojektnamn4 = new javax.swing.JTextField();
        Txtbeskrivning4 = new javax.swing.JTextField();
        Txtstartdatum4 = new javax.swing.JTextField();
        Txtslutdatum4 = new javax.swing.JTextField();
        Txtkostnad4 = new javax.swing.JTextField();
        Txtstatus4 = new javax.swing.JTextField();
        Txtprioritet4 = new javax.swing.JTextField();
        TxtStartdatummain = new javax.swing.JTextField();
        Txtslutdatummain = new javax.swing.JTextField();
        TxtKostnadmain = new javax.swing.JTextField();
        Txtstatusmain = new javax.swing.JTextField();
        Txtpriomain = new javax.swing.JTextField();
        Txtstartdatum1 = new javax.swing.JTextField();
        Txtslutdatum1 = new javax.swing.JTextField();
        Txtkostnad1 = new javax.swing.JTextField();
        Txtstatus1 = new javax.swing.JTextField();
        Txtprioritet1 = new javax.swing.JTextField();
        Txtbeskrivning3 = new javax.swing.JTextField();
        Txtstatus2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Txtprojekt1.setColumns(20);
        Txtprojekt1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Txtprojekt1.setRows(5);
        Txtprojekt1.setText("Projekt 1");
        jScrollPane1.setViewportView(Txtprojekt1);

        Txtprojekt2.setColumns(20);
        Txtprojekt2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Txtprojekt2.setRows(5);
        Txtprojekt2.setText("Projekt 2");
        jScrollPane2.setViewportView(Txtprojekt2);

        Txtprojekt3.setColumns(20);
        Txtprojekt3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Txtprojekt3.setRows(5);
        Txtprojekt3.setText("Projekt 3");
        jScrollPane3.setViewportView(Txtprojekt3);

        Txtprojekt4.setColumns(20);
        Txtprojekt4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Txtprojekt4.setRows(5);
        Txtprojekt4.setText("Projekt 4");
        jScrollPane4.setViewportView(Txtprojekt4);

        Txtbeskrivning.setText("Beskrivning");
        Txtbeskrivning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtbeskrivningActionPerformed(evt);
            }
        });

        Txtbeskrivning1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtbeskrivning1ActionPerformed(evt);
            }
        });

        Txtprojektnamn.setText("Projektnamn");

        Txtprojektnamn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtprojektnamn1ActionPerformed(evt);
            }
        });

        Txtprojektnamn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtprojektnamn2ActionPerformed(evt);
            }
        });

        Txtbeskrivning4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtbeskrivning4ActionPerformed(evt);
            }
        });

        Txtstartdatum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtstartdatum4ActionPerformed(evt);
            }
        });

        TxtStartdatummain.setText("Startdatum");

        Txtslutdatummain.setText("Slutdatum");

        TxtKostnadmain.setText("Kostnad");

        Txtstatusmain.setText("Status");
        Txtstatusmain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtstatusmainActionPerformed(evt);
            }
        });

        Txtpriomain.setText("Prioritet");

        Txtstartdatum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtstartdatum1ActionPerformed(evt);
            }
        });

        Txtkostnad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtkostnad1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Txtprojektnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txtprojektnamn1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(Txtbeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Txtbeskrivning1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Txtslutdatummain, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                                .addComponent(TxtKostnadmain)
                                                .addComponent(Txtstatusmain)
                                                .addComponent(Txtpriomain))
                                            .addComponent(TxtStartdatummain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Txtslutdatum1)
                                            .addComponent(Txtkostnad1)
                                            .addComponent(Txtstatus1)
                                            .addComponent(Txtprioritet1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                            .addComponent(Txtstartdatum1))))
                                .addGap(1, 1, 1)))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Txtstartdatum2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txtprojektnamn2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txtslutdatum2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txtkostnad2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txtstatus2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txtprioritet2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Txtbeskrivning2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2))))))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Txtprioritet3, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(Txtslutdatum3)
                    .addComponent(Txtprojektnamn3)
                    .addComponent(Txtstartdatum3)
                    .addComponent(Txtstatus3)
                    .addComponent(Txtbeskrivning3)
                    .addComponent(Txtkostnad3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Txtprojektnamn4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(Txtstartdatum4)
                                    .addComponent(Txtbeskrivning4)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Txtslutdatum4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Txtkostnad4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Txtstatus4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Txtprioritet4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1500, 1500, 1500))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Txtprojektnamn4)
                                .addGap(153, 153, 153))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Txtprojektnamn3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txtprojektnamn2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Txtbeskrivning3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txtbeskrivning4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Txtstartdatum3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Txtstartdatum4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Txtstartdatum2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Txtstartdatum1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TxtStartdatummain, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(Txtslutdatum4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Txtkostnad4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txtstatus4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Txtprioritet4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(484, 484, 484))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txtprojektnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txtprojektnamn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txtbeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txtbeskrivning1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txtbeskrivning2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Txtslutdatum1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txtslutdatum2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txtslutdatum3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Txtkostnad2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txtkostnad3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(Txtstatus3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Txtprioritet3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Txtslutdatummain)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(Txtkostnad1))
                                    .addComponent(TxtKostnadmain, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Txtstatus1)
                                            .addComponent(Txtstatus2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(Txtstatusmain))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Txtprioritet1)
                                        .addComponent(Txtprioritet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Txtpriomain))
                                .addGap(483, 483, 483))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtbeskrivningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtbeskrivningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtbeskrivningActionPerformed

    private void Txtprojektnamn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtprojektnamn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtprojektnamn1ActionPerformed

    private void Txtbeskrivning1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtbeskrivning1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Txtbeskrivning1ActionPerformed

    private void Txtbeskrivning4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtbeskrivning4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtbeskrivning4ActionPerformed

    private void TxtstatusmainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtstatusmainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtstatusmainActionPerformed

    private void Txtprojektnamn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtprojektnamn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtprojektnamn2ActionPerformed

    private void Txtkostnad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtkostnad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtkostnad1ActionPerformed

    private void Txtstartdatum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtstartdatum4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtstartdatum4ActionPerformed

    private void Txtstartdatum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtstartdatum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtstartdatum1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void minaprojekt(){
        try {
    String projektsql = "SELECT projektnamn,beskrivning,startdatum,slutdatum,kostnad,status,prioritet FROM projekt "
            + "JOIN ans_proj ON projekt.pid = ans_proj.pid "
            + "JOIN anstalld ON ans_proj.aid = anstalld.aid "
            + "WHERE anstalld.epost = '" + inloggadAnvandare + "'";

    ArrayList<HashMap<String, String>> allt = idb.fetchRows(projektsql);

    if (allt != null && !allt.isEmpty()) {
        for (int i = 0; i < allt.size(); i++) {
            HashMap<String, String> projekt = allt.get(i);

            switch (i) {
                case 0:
                    Txtprojektnamn1.setText(projekt.get("projektnamn"));
                    Txtbeskrivning1.setText(projekt.get("beskrivning"));
                    Txtstartdatum1.setText(projekt.get("startdatum"));
                    Txtslutdatum1.setText(projekt.get("slutdatum"));
                    Txtkostnad1.setText(projekt.get("kostnad"));
                    Txtstatus1.setText(projekt.get("status"));
                    Txtprioritet1.setText(projekt.get("prioritet"));
                    break;

                case 1:
                    Txtprojektnamn2.setText(projekt.get("projektnamn"));
                    Txtbeskrivning2.setText(projekt.get("beskrivning"));
                    Txtstartdatum2.setText(projekt.get("startdatum"));
                    Txtslutdatum2.setText(projekt.get("slutdatum"));
                    Txtkostnad2.setText(projekt.get("kostnad"));
                    Txtstatus2.setText(projekt.get("status"));
                    Txtprioritet2.setText(projekt.get("prioritet"));
                    break;
                    case 2:
                    Txtprojektnamn3.setText(projekt.get("projektnamn"));
                    Txtbeskrivning3.setText(projekt.get("beskrivning"));
                    Txtstartdatum3.setText(projekt.get("startdatum"));
                    Txtslutdatum3.setText(projekt.get("slutdatum"));
                    Txtkostnad3.setText(projekt.get("kostnad"));
                    Txtstatus3.setText(projekt.get("status"));
                    Txtprioritet3.setText(projekt.get("prioritet"));
                    break;
                    case 3:
                    Txtprojektnamn3.setText(projekt.get("projektnamn"));
                    Txtbeskrivning3.setText(projekt.get("beskrivning"));
                    Txtstartdatum3.setText(projekt.get("startdatum"));
                    Txtslutdatum3.setText(projekt.get("slutdatum"));
                    Txtkostnad3.setText(projekt.get("kostnad"));
                    Txtstatus3.setText(projekt.get("status"));
                    Txtprioritet3.setText(projekt.get("prioritet"));
                    break;

                // Hantera fler fall om det behövs

                default:
                    break;
            }
        }
    } 
} catch (Exception e) {
   
}

   /**
 * Main method to launch the application.
 *
 * @param args Command-line arguments.
 */
//public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(MinaProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(MinaProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(MinaProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(MinaProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            //new MinaProjekt().setVisible(true); // Visa formuläret
        }
    });
}

        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtKostnadmain;
    private javax.swing.JTextField TxtStartdatummain;
    private javax.swing.JTextField Txtbeskrivning;
    private javax.swing.JTextField Txtbeskrivning1;
    private javax.swing.JTextField Txtbeskrivning2;
    private javax.swing.JTextField Txtbeskrivning3;
    private javax.swing.JTextField Txtbeskrivning4;
    private javax.swing.JTextField Txtkostnad1;
    private javax.swing.JTextField Txtkostnad2;
    private javax.swing.JTextField Txtkostnad3;
    private javax.swing.JTextField Txtkostnad4;
    private javax.swing.JTextField Txtpriomain;
    private javax.swing.JTextField Txtprioritet1;
    private javax.swing.JTextField Txtprioritet2;
    private javax.swing.JTextField Txtprioritet3;
    private javax.swing.JTextField Txtprioritet4;
    private javax.swing.JTextArea Txtprojekt1;
    private javax.swing.JTextArea Txtprojekt2;
    private javax.swing.JTextArea Txtprojekt3;
    private javax.swing.JTextArea Txtprojekt4;
    private javax.swing.JTextField Txtprojektnamn;
    private javax.swing.JTextField Txtprojektnamn1;
    private javax.swing.JTextField Txtprojektnamn2;
    private javax.swing.JTextField Txtprojektnamn3;
    private javax.swing.JTextField Txtprojektnamn4;
    private javax.swing.JTextField Txtslutdatum1;
    private javax.swing.JTextField Txtslutdatum2;
    private javax.swing.JTextField Txtslutdatum3;
    private javax.swing.JTextField Txtslutdatum4;
    private javax.swing.JTextField Txtslutdatummain;
    private javax.swing.JTextField Txtstartdatum1;
    private javax.swing.JTextField Txtstartdatum2;
    private javax.swing.JTextField Txtstartdatum3;
    private javax.swing.JTextField Txtstartdatum4;
    private javax.swing.JTextField Txtstatus1;
    private javax.swing.JTextField Txtstatus2;
    private javax.swing.JTextField Txtstatus3;
    private javax.swing.JTextField Txtstatus4;
    private javax.swing.JTextField Txtstatusmain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
