/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;

/**
 *
 * @author jamie
 */
public class ChefTaBortHandlaggare extends javax.swing.JFrame {
    
    private InfDB idb;
    private String inloggadAnvandare;

    /**
     * Creates new form ChefTaBortHandlaggare
     */
    public ChefTaBortHandlaggare(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        txtAnstalldasNamn.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAnstalldasNamn = new javax.swing.JLabel();
        txtAnstalldasNamn = new javax.swing.JTextField();
        btnRemovePerson = new javax.swing.JButton();
        lblFornamn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblAnstalldasNamn.setText("Ta bort handläggare:");

        txtAnstalldasNamn.setText("placeholder");
        txtAnstalldasNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnstalldasNamnActionPerformed(evt);
            }
        });

        btnRemovePerson.setText("OK");
        btnRemovePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovePersonActionPerformed(evt);
            }
        });

        lblFornamn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblFornamn.setText("För in förnamn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAnstalldasNamn)
                        .addGap(18, 18, 18)
                        .addComponent(txtAnstalldasNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnRemovePerson))
                    .addComponent(lblFornamn))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblFornamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAnstalldasNamn)
                    .addComponent(txtAnstalldasNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnRemovePerson)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    

    
    
    private void btnRemovePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovePersonActionPerformed
                                                       

    try {
        // Hämta namnet från textfältet
        String handlaggarNamn = txtAnstalldasNamn.getText().trim();

        if (handlaggarNamn.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ange ett namn!");
            return;
        }

        // Kontrollera om namnet finns i databasen och hämta handläggarens ID
        String kontrollSql = "SELECT aid FROM anstalld WHERE fornamn = '" + handlaggarNamn + "'";
        String handlaggarID = idb.fetchSingle(kontrollSql);

        if (handlaggarID == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingen handläggare med namnet \"" + handlaggarNamn + "\" hittades.");
            return;
        }

        // Ta bort kopplingen mellan handläggaren och projektet
        String deleteSql = "DELETE FROM ans_proj WHERE aid = '" + handlaggarID + "' " +
                           "AND pid IN (SELECT pid FROM projekt WHERE projektchef IN " +
                           "(SELECT aid FROM anstalld WHERE epost = '" + inloggadAnvandare + "'))";
        idb.delete(deleteSql);

        javax.swing.JOptionPane.showMessageDialog(this, "Handläggaren \"" + handlaggarNamn + "\" har tagits bort från projektet.");

        // Töm textfältet efter borttagning
        txtAnstalldasNamn.setText("");

    } catch (InfException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Fel vid borttagning: " + e.getMessage());
    }


    }//GEN-LAST:event_btnRemovePersonActionPerformed

    private void txtAnstalldasNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnstalldasNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnstalldasNamnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChefTaBortHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChefTaBortHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChefTaBortHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChefTaBortHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ChefTaBortHandlaggare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemovePerson;
    private javax.swing.JLabel lblAnstalldasNamn;
    private javax.swing.JLabel lblFornamn;
    private javax.swing.JTextField txtAnstalldasNamn;
    // End of variables declaration//GEN-END:variables
}
