/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import oru.inf.InfDB;
import oru.inf.InfException;


/**
 *
 * @author jamie
 */
public class ChefLäggTillHandläggare extends javax.swing.JFrame {
    
    
    private InfDB idb;
    private String inloggadAnvandare;

    /**
     * Creates new form ChefLäggTillHandläggare
     */
    public ChefLäggTillHandläggare(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        tfFornamn.setText("");
        tfEfternamn.setText("");
        tfProjektnamn.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFornamn = new javax.swing.JLabel();
        lblEfternamn = new javax.swing.JLabel();
        lblProjektnamn = new javax.swing.JLabel();
        lblLaggTillHandlaggare = new javax.swing.JLabel();
        tfFornamn = new javax.swing.JTextField();
        tfEfternamn = new javax.swing.JTextField();
        tfProjektnamn = new javax.swing.JTextField();
        btnLaggTillHandlaggare = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblFornamn.setText("Förnamn:");

        lblEfternamn.setText("Efternamn:");

        lblProjektnamn.setText("Projektnamn:");

        lblLaggTillHandlaggare.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLaggTillHandlaggare.setText("Lägg till handläggare");

        tfFornamn.setText("Placeholder");

        tfEfternamn.setText("Placeholder");

        tfProjektnamn.setText("Placeholder");

        btnLaggTillHandlaggare.setText("OK");
        btnLaggTillHandlaggare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillHandlaggareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblProjektnamn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfProjektnamn, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnLaggTillHandlaggare, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEfternamn, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(11, 11, 11)
                                .addComponent(tfEfternamn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFornamn)
                                .addGap(32, 32, 32)
                                .addComponent(tfFornamn))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLaggTillHandlaggare)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(232, 232, 232))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLaggTillHandlaggare)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornamn)
                    .addComponent(tfFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEfternamn)
                    .addComponent(tfEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjektnamn)
                    .addComponent(tfProjektnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnLaggTillHandlaggare)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLaggTillHandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillHandlaggareActionPerformed
        try {
            
            String fornamn = tfFornamn.getText().trim();
            String efternamn = tfEfternamn.getText().trim();
            
            
            if (fornamn.isEmpty() || efternamn.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog (this, "Fyll i både förnamn och efternamn!");
                return;
                
            }
            
            String sqlHittaAnstalld = "SELECT aid FROM anstalld WHERE fornamn = '" + fornamn + "' AND efternamn = '" + efternamn + "'";
            String handlaggarID = idb.fetchSingle(sqlHittaAnstalld);
            
            
            if (handlaggarID == null) {
                javax.swing.JOptionPane.showMessageDialog (this, "Ingen anställd med namnet \"" + fornamn + " " + efternamn + "\" hittades.");
                return;
            }
            
            
            String sqlHittaProjekt = "SELECT pid FROM projekt WHERE projektchef IN (SELECT aid FROM anstalld WHERE epost = '" + inloggadAnvandare + "')";
            String projektID = idb.fetchSingle(sqlHittaProjekt);
            
            
            if (projektID == null) {
                javax.swing.JOptionPane.showMessageDialog (this, "Inget projekt hittades för den inloggade projektchefen.");
                return;
            }
            
            String sqlLaggTillKoppling = "INSERT INTO ans_proj (aid, pid) VALUES ('" + handlaggarID + "', '" + projektID + "')";
            idb.insert(sqlLaggTillKoppling);
            
            javax.swing.JOptionPane.showMessageDialog (this, "Handläggaren \"" + fornamn + " " + efternamn + "\" har lagts till i projektet!");
            
            tfFornamn.setText("");
            tfEfternamn.setText("");
            
            
            if (getOwner() instanceof ProjektChefSeMinaProjekt) {
                ((ProjektChefSeMinaProjekt) getOwner()).fyllHandlaggareTabell();
            }
            
            
            
        } catch (InfException e) {
            javax.swing.JOptionPane.showMessageDialog (this, "Fel vid lägg till: " + e.getMessage());
        }
            
            
    }//GEN-LAST:event_btnLaggTillHandlaggareActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChefLäggTillHandläggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChefLäggTillHandläggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChefLäggTillHandläggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChefLäggTillHandläggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ChefLäggTillHandläggare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTillHandlaggare;
    private javax.swing.JLabel lblEfternamn;
    private javax.swing.JLabel lblFornamn;
    private javax.swing.JLabel lblLaggTillHandlaggare;
    private javax.swing.JLabel lblProjektnamn;
    private javax.swing.JTextField tfEfternamn;
    private javax.swing.JTextField tfFornamn;
    private javax.swing.JTextField tfProjektnamn;
    // End of variables declaration//GEN-END:variables
}
