/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;


import javax.swing.table.DefaultTableModel;
import ngo2024.Validator;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;




/**
 *
 * @author jamie
 */
public class PartnerSamarbete extends javax.swing.JFrame {
    
    
    
    private InfDB idb;
    private String inloggadAnvandare;

    /**
     * Creates new form PartnerSamarbete
     */
    public PartnerSamarbete(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        visapartnerinfofylltabell();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
     //Metod för att hitta samtliga partners som hör till projektet.
   

        public void visapartnerinfofylltabell() {
    try {
        // SQL-fråga för att hämta partners baserat på inloggadAnvandare (epostadress)
        String sqlPartner = "SELECT partner.namn, partner.kontaktperson, partner.kontaktepost, partner.telefon, partner.adress, partner.branch " +
                            "FROM partner " +
                            "JOIN projekt_partner ON partner.pid = projekt_partner.partner_pid " +
                            "JOIN projekt ON projekt.pid = projekt_partner.pid " +
                            "JOIN ans_proj ON ans_proj.pid = projekt.pid " +
                            "JOIN anstalld ON anstalld.aid = ans_proj.aid " +
                            "WHERE anstalld.epost = '" + inloggadAnvandare + "'";

        // Utför SQL-frågan och hämta resultatet
        ArrayList<HashMap<String, String>> resultat = idb.fetchRows(sqlPartner);

        // Om inga partners hittas, visa ett meddelande
        if (resultat == null || resultat.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Inga partners hittades.");
            return;
        }

        // Skapa en tabellmodell för att visa resultaten i en tabell
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("namn");
        model.addColumn("kontaktperson");
        model.addColumn("kontaktepost");
        model.addColumn("telefon");
        model.addColumn("adress");
        model.addColumn("branch");

        // Fyll tabellen med data från resultatet
        for (HashMap<String, String> rad : resultat) {
            model.addRow(new Object[]{
                rad.get("namn"),
                rad.get("kontaktperson"),
                rad.get("kontaktepost"),
                rad.get("telefon"),
                rad.get("adress"),
                rad.get("branch")
            });
        }

        // Sätt modellen till din tabell (t.ex. tblprojekt)
        tblprojekt.setModel(model);

    } catch (InfException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Fel vid hämtning av partners: " + e.getMessage());
    }
}


        
        
        
        
        
        
        
        
        
        
        
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblprojekt = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblprojekt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(tblprojekt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartnerSamarbete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartnerSamarbete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartnerSamarbete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartnerSamarbete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PartnerSamarbete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblprojekt;
    // End of variables declaration//GEN-END:variables
}
