/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
/**
 * This class allows users to search for projects within a specified date range.
 * The search is performed on an InfDB database and results are displayed in a table.
 * Users can specify a start date and end date to filter the projects.
 * 
 * Author: budim
 */
public class SökProjektPåDatum extends javax.swing.JFrame {
    private InfDB idb;
    private String inloggadAnvandare;

     /**
     * Creates a new form SökProjektPåDatum.
     * 
     * @param idb the InfDB database instance used to retrieve data.
     * @param inloggadAnvandare the logged-in user's identifier.
     */
    public SökProjektPåDatum(InfDB idb, String inloggadAnvandare) {
        initComponents();
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[]{
                    "Pid","Projektnamn", "Beskrivning", "Startdatum", "Slutdatum", "Kostnad", "Status", "Prioritet", "Projektchef", "Land"
                }
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        StartDatumFält = new javax.swing.JFormattedTextField();
        SlutDatumFält = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SökKnapp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sök på projekt via datum");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        StartDatumFält.setText("YYYY-MM-DD");
        StartDatumFält.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartDatumFältActionPerformed(evt);
            }
        });

        SlutDatumFält.setText("YYYY-MM-DD");

        jLabel2.setText("Datum från:");

        jLabel3.setText("Datum till:");

        SökKnapp.setText("Sök...");
        SökKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SökKnappActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(199, 199, 199)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(StartDatumFält, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SlutDatumFält, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SökKnapp)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartDatumFält, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlutDatumFält, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SökKnapp))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartDatumFältActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartDatumFältActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartDatumFältActionPerformed
/**
     * Event handler for the search button.
     * Triggered when the user clicks the SökKnapp button.
     * 
     * @param evt the ActionEvent triggered by the user.
     */
    private void SökKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SökKnappActionPerformed
performSearch();        
    }//GEN-LAST:event_SökKnappActionPerformed
 /**
     * Performs a search for projects within the specified date range.
     * Validates the input dates and queries the database for matching projects.
     * Displays the results in a table.
     */
    private void performSearch() {
        String startDatum = StartDatumFält.getText();
        String slutDatum = SlutDatumFält.getText();
        if 
                (startDatum.isEmpty() || slutDatum.isEmpty() ||
                !Validator.isValidDate(startDatum) || !Validator.isValidDate(slutDatum)) {
            JOptionPane.showMessageDialog(this, "Vänligen ange giltiga datum i formatet YYYY-MM-DD.");
            return;
        }
        String sql = "SELECT pid, projektnamn, beskrivning, startdatum, slutdatum, kostnad, statud, prioritet, projektchef, land "
                + "FROM projekt "
                + "WHERE startdatum >= '" + startDatum + "' "
                + "AND slutdatum <= '" + slutDatum + "' "
                + "AND statud = 'Pågående'";
        try {
            ArrayList<HashMap<String, String>> results = idb.fetchRows(sql);
            if (results == null || results.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Inga projekt hittades för angiven period, sök med nya datum.");
                return;
            }
            populateTable(results);
        } catch (InfException a) {
            JOptionPane.showMessageDialog(this, "Ett fel inträffade vid hämtning av data från databasen." + a.getMessage());
        }
    }
    /**
     * Populates the table with the results of the search.
     * 
     * @param results the list of projects returned from the database.
     */
    private void populateTable(ArrayList<HashMap<String, String>> results) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (HashMap<String, String> row : results) {
            model.addRow(new Object[]{
                row.get("pid"),
                row.get("projektnamn"),
                row.get("beskrivning"),
                row.get("startdatum"),
                row.get("slutdatum"),
                row.get("kostnad"),
                row.get("status"),
                row.get("prioritet"),
                row.get("projektchef"),
                row.get("land")                
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SökProjektPåDatum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SökProjektPåDatum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SökProjektPåDatum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SökProjektPåDatum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new SökProjektPåDatum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField SlutDatumFält;
    private javax.swing.JFormattedTextField StartDatumFält;
    private javax.swing.JButton SökKnapp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
